# -*- coding: utf-8 -*-
"""agenticai_ui.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sukOPeGCj9-3pWP5YwHpms0PzznHmnNf
"""

import streamlit as st
import pandas as pd
import requests

from agenticai_project import (
    agentic_step,
    df,
    action_rewards,
    ACTIONS
)

# -------------------------------------------------
# PAGE CONFIG
# -------------------------------------------------
st.set_page_config(
    page_title="Spotify-Style Agentic Recommender",
    page_icon="🎧",
    layout="wide"
)

# -------------------------------------------------
# SPOTIFY-LIKE CSS
# -------------------------------------------------
st.markdown(
    """
    <style>
    body {
        background-color: #121212;
        color: white;
    }

    .block-container {
        padding-top: 1.5rem;
    }

    .spotify-card {
        background-color: #181818;
        padding: 16px;
        border-radius: 12px;
        margin-bottom: 16px;
        transition: background-color 0.3s;
    }

    .spotify-card:hover {
        background-color: #282828;
    }

    .song-title {
        font-size: 20px;
        font-weight: 700;
        margin-bottom: 4px;
    }

    .song-meta {
        color: #b3b3b3;
        font-size: 14px;
    }

    .badge {
        display: inline-block;
        background-color: #1DB954;
        color: black;
        padding: 2px 8px;
        border-radius: 20px;
        font-size: 12px;
        font-weight: 600;
        margin-top: 6px;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# -------------------------------------------------
# HEADER
# -------------------------------------------------
st.markdown("## 🎧 Spotify-Like Agentic Music Recommender")
st.caption("Agentic AI · Reinforcement Learning · iTunes Album Art")

st.markdown("---")

# -------------------------------------------------
# ITUNES ALBUM COVER
# -------------------------------------------------
@st.cache_data(show_spinner=False)
def fetch_album_cover(track, artist):
    try:
        query = f"{track} {artist}".replace(" ", "+")
        url = f"https://itunes.apple.com/search?term={query}&entity=song&limit=1"
        res = requests.get(url, timeout=5).json()

        if res["resultCount"] > 0:
            return res["results"][0].get("artworkUrl100", "")
    except:
        pass
    return ""

# -------------------------------------------------
# SIDEBAR (SPOTIFY STYLE)
# -------------------------------------------------
with st.sidebar:
    st.markdown("### 🎛 Controls")

    user_ids = df["user_id"].unique().tolist()
    user_id = st.selectbox("User", user_ids)

    num_recs = st.slider("Recommendations", 1, 10, 5)

    generate = st.button("▶ Play Recommendations")

# -------------------------------------------------
# MAIN CONTENT
# -------------------------------------------------
if generate:
    st.success("🎶 Fresh recommendations ready")

    results = [agentic_step(user_id) for _ in range(num_recs)]
    results_df = pd.DataFrame(results)

    # -------------------------------------------------
    # SONG CARDS
    # -------------------------------------------------
    for _, row in results_df.iterrows():
        cover = fetch_album_cover(row["song"], row["artist"])

        col1, col2 = st.columns([1, 6])

        with col1:
            if cover:
                st.image(cover, width=90)
            else:
                st.image(
                    "https://via.placeholder.com/150?text=No+Cover",
                    width=90
                )

        with col2:
            st.markdown(
                f"""
                <div class="spotify-card">
                    <div class="song-title">{row['song']}</div>
                    <div class="song-meta">
                        {row['artist']} · {row['playlist']}
                    </div>
                    <div class="badge">
                        {row['strategy']} · Reward {row['reward']}
                    </div>
                </div>
                """,
                unsafe_allow_html=True
            )